// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using csuwf.PaperManagement.Common;
using csuwf.PaperManagement.Papers;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace csuwf.PaperManagement.Papers;

public interface IPaperAppService : IApplicationService
{
    Task<PaperDto> GetAsync(Guid id);

    Task<PagedResultDto<PaperDto>> GetListAsync(PagedSortedAndFilteredResultRequestDto input);

    Task<PaperDto> CreateAsync(CreateUpdatePaperDto input);

    Task<PaperDto> UpdateAsync(Guid id, CreateUpdatePaperDto input);

    Task<PaperDto> DeleteAsync(Guid id);
}
