// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using csuwf.PaperManagement.Papers;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace csuwf.PaperManagement.Papers;

public enum PaperStatus
{
    UnProcessed = 0,
    Processed = 1,
    Deprecated = 2
}
