// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using csuwf.PaperManagement.Common;
using csuwf.PaperManagement.Users;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;

// ReSharper disable once CheckNamespace
namespace csuwf.PaperManagement.Users;

public interface IUserAppService : IApplicationService
{
    Task<UserDto> GetAsync(Guid id);

    Task<PagedResultDto<UserDto>> GetListAsync(PagedSortedAndFilteredResultRequestDto input);
}
