// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using csuwf.PaperManagement.Users;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace csuwf.PaperManagement.Users;

public class UserDto
{
    public string Id { get; set; }

    public string Email { get; set; }

    public string Username { get; set; }
}
