// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using csuwf.PaperManagement.Common;
using csuwf.PaperManagement.Users;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace csuwf.PaperManagement.Users;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IUserAppService), typeof(UserClientProxy))]
public partial class UserClientProxy : ClientProxyBase<IUserAppService>, IUserAppService
{
    public virtual async Task<UserDto> GetAsync(Guid id)
    {
        return await RequestAsync<UserDto>(nameof(GetAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }

    public virtual async Task<PagedResultDto<UserDto>> GetListAsync(PagedSortedAndFilteredResultRequestDto input)
    {
        return await RequestAsync<PagedResultDto<UserDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PagedSortedAndFilteredResultRequestDto), input }
        });
    }
}
