// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using csuwf.PaperManagement.Common;
using csuwf.PaperManagement.Statistics;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace csuwf.PaperManagement.Statistics;

public class GetWorkerResolveCountDto : PagedSortedAndFilteredResultRequestDto
{
    public DateTime StartTime { get; set; }

    public DateTime EndTime { get; set; }
}
