// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using csuwf.PaperManagement.Statistics;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace csuwf.PaperManagement.Statistics;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IStatisticAppService), typeof(StatisticClientProxy))]
public partial class StatisticClientProxy : ClientProxyBase<IStatisticAppService>, IStatisticAppService
{
    public virtual async Task<int> GetTodayResolveCountAsync()
    {
        return await RequestAsync<int>(nameof(GetTodayResolveCountAsync));
    }

    public virtual async Task<PagedResultDto<WorkerResolveCountDto>> GetWorkerResolveCountAsync(GetWorkerResolveCountDto input)
    {
        return await RequestAsync<PagedResultDto<WorkerResolveCountDto>>(nameof(GetWorkerResolveCountAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetWorkerResolveCountDto), input }
        });
    }
}
