// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using csuwf.PaperManagement.Statistics;
using System;
using System.Collections.Generic;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.ObjectExtending;

// ReSharper disable once CheckNamespace
namespace csuwf.PaperManagement.Statistics;

public class WorkerResolveCountDto
{
    public string WorkerName { get; set; }

    public int WorkerId { get; set; }

    public int ResolveCount { get; set; }
}
