name: Build and Push Docker Image

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Docker Login  
      uses: docker/login-action@v3.3.0
      with:  
        username: ${{ secrets.DOCKER_HUB_USERNAME }}  
        password: ${{ secrets.DOCKER_HUB_TOKEN }}  
    
    - name: Build and push Docker images
      uses: docker/build-push-action@v6.9.0
      with:
        build-args: BUILD_CONFIGURATION=Release
        tags: chhin/wfpapermanagementhttpapihost:latest
        labels: com.microsoft.visual-studio.project-name=Wf.PaperManagement.HttpApi.Host
        file: src/Wf.PaperManagement.HttpApi.Host/Dockerfile
        push: true

